version: '3'
services:
  backend-token:
    depends_on:
      - database-token
    build: .
    command: "npm run start"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DB_HOST=localhost
      - DB_NAME=token_api
      - DB_URL=postgres://docker:docker@database-token:5432/token_api
    expose:
      - "3001"
    ports:
      - "3001:3001"

  database-token:
    image: postgres:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: token_api
    ports:
      - "5431:5432"
    volumes:
      - ./data-token-api:/var/lib/postgresql/data

volumes:
  data-token-api: